name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      js-filename: ${{ steps.js_filename.outputs.js_filename_step }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Output JS filename
        id: js_filename
        run: find dist/assets/*.js -type f -execdir echo 'js_filename_step={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: app-artifact
          path: dist
      - name: Log JS filename
        run: echo "${{ needs.build.outputs.js-filename }}"
      - name: Deploy
        run: echo "Deploying..."
